task2
echekholskiy/Task2 pull request #1
Opened 2021-05-30 15:29 UTC by echekholskiy

2021-05-31 08:13 UTC, asushkov-github requested changes

2021-05-31 08:13 UTC, asushkov-github commented on Task2/Utils/CsvManager.cs
> +            if (Directory.Exists("CSV"))
"CSV"

2021-05-31 08:13 UTC, asushkov-github commented on YandexMarket/Pages/CategoryPage.cs
> +            :base(By.XPath($"//h1[contains(text(), '{nameOfCategory}')]"), "CategoryPage"){}
Please don't use such concrete path with `h1`

2021-05-31 08:13 UTC, asushkov-github commented on YandexMarket/Pages/LoginPage.cs
> +        public LoginPage() : base(By.XPath("//*[@class='AuthSocialBlock-title']"), "LoginPage"){}
`//*[@class='AuthSocialBlock']`

2021-05-31 08:13 UTC, asushkov-github commented on YandexMarket/Pages/LoginPage.cs
> +            ElementFactory.GetButton(By.XPath("//*[@class='passp-button passp-sign-in-button']//button"),
`//button[@type='submit']`

2021-05-31 11:13 UTC, asushkov-github commented on Task2/Tests/TestFixture.cs
> +            Password = _credentials.GetValue<string>("password");
Try to use IConfiguration for working with configs
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration?view=dotnet-plat-ext-5.0

2021-05-31 11:23 UTC, asushkov-github commented on YandexMarket/Pages/MainPage.cs
> +            var indexOfRandomCategory = new Random().Next(0, listOfPopularCategoryNames.Count - 1);
Create `RandomizeExtensions` class and use its extension `listOfPopularCategoryNames.GetRandomValue()`

2021-05-31 11:26 UTC, asushkov-github commented on YandexMarket/Pages/MainPage.cs
> +            });
`return _listOfCategories.Select(c => c..GetText());`

2021-05-31 11:29 UTC, asushkov-github commented on YandexMarket/Pages/MainPage.cs
> +                listOfCategoryLinks.Add(category.GetAttribute("href"));
Create ElementExtensions and use method `category.GetHrefAttribute()`

2021-05-31 11:30 UTC, asushkov-github commented on YandexMarket/Pages/MainPage.cs
> +            return listOfCategoryLinks;
return _listOfCategories.Select(c => c.GetHrefAttribute());

2021-05-31 11:33 UTC, asushkov-github commented on YandexMarket/Pages/MainPage.cs
> +        public MainPage() : base(By.XPath("//h3[contains(text(), 'Покупки на Маркете')]"), "MainPage") {}
Put {} braces on new string.

2021-05-31 12:48 UTC, echekholskiy commented on Task2/Tests/TestFixture.cs
> +        private readonly JsonSettingsFile _credentials = new(@"..\\..\\..\\..\\Resources\\credentials.json");
could not find a method that returns root catolog. So can use:
Path.Combine(Directory.GetCurrentDirectory(), "..\\..\\..\\Resources\\credentials.json")

2021-05-31 12:49 UTC, echekholskiy commented on Task2/Tests/TestFixture.cs
> +        protected void Authorization(string login, string password)
done

2021-05-31 12:49 UTC, echekholskiy commented on Task2/Tests/TestFixture.cs
> +            Logger.Instance.Info(string.Join("", categories)); //TODO перенести мб в утилиты
done

2021-05-31 12:49 UTC, echekholskiy commented on Task2/Utils/CsvManager.cs
> +            foreach (var element in list)
done

2021-05-31 12:49 UTC, echekholskiy commented on Task2/Utils/CsvManager.cs
> +            if (Directory.Exists("CSV"))
done

2021-05-31 12:49 UTC, echekholskiy commented on YandexMarket/Pages/CategoryPage.cs
> +            :base(By.XPath($"//h1[contains(text(), '{nameOfCategory}')]"), "CategoryPage"){}
done

2021-05-31 12:50 UTC, echekholskiy commented on YandexMarket/Pages/LoginPage.cs
> +        public LoginPage() : base(By.XPath("//*[@class='AuthSocialBlock-title']"), "LoginPage"){}
done

2021-05-31 12:50 UTC, echekholskiy commented on YandexMarket/Pages/LoginPage.cs
> +            ElementFactory.GetButton(By.XPath("//*[@class='passp-button passp-sign-in-button']//button"),
done

2021-05-31 15:10 UTC, echekholskiy commented on YandexMarket/Pages/MainPage.cs
> +        public MainPage() : base(By.XPath("//h3[contains(text(), 'Покупки на Маркете')]"), "MainPage") {}
done

2021-06-01 09:33 UTC, echekholskiy commented on Task2/Tests/YandexTests.cs
> +            mainPageIsOpened.Should().BeTrue("MainPage is not opened");
done

2021-06-01 09:33 UTC, echekholskiy commented on Task2/Tests/YandexTests.cs
> +            mainPageIsOpened.Should().BeTrue("MainPage is not opened");
done

2021-06-01 09:33 UTC, echekholskiy commented on Task2/Tests/YandexTests.cs
> +            WriteListOfCategoriesToLog(popularCategories);
done

2021-06-01 09:33 UTC, echekholskiy commented on Task2/Tests/YandexTests.cs
> +            WriteAllCategoriesToCsvFile(listOfAllCategories);
done

2021-06-01 09:33 UTC, echekholskiy commented on Task2/Tests/YandexTests.cs
> +                "Сategories from the catalog don't contain all popular categories");
done

2021-06-01 09:33 UTC, echekholskiy commented on Task2/Tests/TestFixture.cs
> +            Password = _credentials.GetValue<string>("password");
done

2021-06-01 09:33 UTC, echekholskiy commented on YandexMarket/Pages/MainPage.cs
> +            var indexOfRandomCategory = new Random().Next(0, listOfPopularCategoryNames.Count - 1);
done

2021-06-01 09:35 UTC, echekholskiy commented on YandexMarket/Pages/MainPage.cs
> +            });
done, but it returns IEnumerable, so I've added toList() method.

2021-06-01 09:35 UTC, echekholskiy commented on YandexMarket/Pages/MainPage.cs
> +                listOfCategoryLinks.Add(category.GetAttribute("href"));
done

2021-06-01 09:35 UTC, echekholskiy commented on YandexMarket/Pages/MainPage.cs
> +            return listOfCategoryLinks;
done

2021-06-01 09:36 UTC, echekholskiy commented on YandexMarket/Pages/MainPage.cs
> +        public MainPage() : base(By.XPath("//h3[contains(text(), 'Покупки на Маркете')]"), "MainPage") {}
done

2021-06-01 09:36 UTC, closed without merging